[package]
name = "bitbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.6.4"
crossbeam-channel = "0.5.13"
slab = "0.4.9"
libc = "0.2.155"